version: '3'

services:
  web:
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/learning
    env_file: .env
    depends_on:
      - database
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'

  database:
    build: 
      context: .
      dockerfile: db.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: learning
    ports:
      - 33066:3306
    volumes:
      - learningdata:/var/lib/mysql 

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 5001:80
    environment:
      - 'PMA_HOST=database'
      - 'PMA_PORT=3306'

# persisted storage
volumes:
  learningdata: